### PR TITLE
Nagios and certification directory enhancemens

### PR DESCRIPTION
**Pull request by mape2k**
This patchset will add some functionality and fix some issues concerning nagios output.
- Fix returncode handling for nagios output (for now only the latest returncode will be used if file list is in use)
- Fix returncode on file not found to UNKNOWN instead of WARNING - this is more common
- Add option to use directory or file pattern which allows to check folders more dynamic without creating a file list
- Add option to summarize output to a single line for nagios. Multiple lines will break NRPE compatibility which is often used with nagios.

### CODE REVIEW

**Comment by Matty9191** [comment]
Thanks for the awesome enhancments!

**Comment by Matty9191** [comment]
Hey mape2k ,

Would you mind merging your changes into version 3.29a? It looks like there are a number of conflicts.

- Ryan

**Comment by mape2k** [comment]
Hey @Matty9191,

i've merged all changes from 3.29a to my commit which could not be merged automatically. Is this okay for you?

**Comment by Matty9191** [comment]
Awesome work thanks!!!!!!!!!!

**Pull request merged**
